
stages:
  - build
  - test
  - deploy 

# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml

build-back:
  stage: build
  # Select image from https://hub.docker.com/_/php/
  image: php:latest

  # Select what we should cache between builds
  cache:
    paths:
      - vendor/
  script: echo "Define your build script!"
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
    # Install PHP extensions
    - docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2 opcache
    # Install & enable Xdebug for code coverage reports
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    # Install and run Composer
    - export COMPOSER_HOME="$CI_PROJECT_DIR/vendor/bin"
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd api/
    - composer install

  # Bring in any services we need https://docs.gitlab.com/ee/ci/services/index.html
  # See http://docs.gitlab.com/ee/ci/services/README.html for examples.
  services:
    - mariadb:latest

  # Set any variables we need
  variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: db
    MYSQL_ROOT_PASSWORD: root

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  script: echo "Define your deployment script!"
  only:
      refs:
        - develop
      variables:
        - $CI_MERGE_REQUEST_ID

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

