import React, {useEffect} from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import NavBar from '@/components/menu/NavBar';
import Image from 'next/image';
import bgHome from '@/assets/images/bg-home.jpg';
import styles from '@/pages/trip/TripDetails.module.css'
import Footer from '@/components/footer/Footer';
import RowTripDetails from '@/components/rowTripDetails/RowTripDetails';
import {jsPDF, HTMLOptionImage} from 'jspdf';
import {toPng, toCanvas} from 'html-to-image';
import TripService from '../../../_services/trip';

type props = {
	html?: React.MutableRefObject<HTMLDivElement>;
};

function Id(html: any) {
	const [trip, setTrip] = React.useState<any>(null);
	const router = useRouter();
	useEffect(() => {
		if(!router.isReady) return;
		const getTripDetails = async () => {
			const tripService = new TripService();
			try {
				const response = await tripService.getTripById(router.query.id);
				if (response.status === 200) {
					return response.data;
				}
			} catch (error) {
				console.log(error);
			}
		};

		getTripDetails().then((trip) => {
			setTrip(trip);
		});

	}, [router.isReady]);

	const generatePdf = () => {
		const doc = new jsPDF();
		// @ts-ignore
		let title = doc.splitTextToSize(document.getElementById('title').innerText, 200);
		// @ts-ignore
		let split1 = doc.splitTextToSize(document.getElementById('transport').innerText, 200);
		// @ts-ignore
		let split2 = doc.splitTextToSize(document.getElementById('logement').innerText, 200);
		// @ts-ignore
		let split3 = doc.splitTextToSize(document.getElementById('activite').innerText, 200);

		doc.text(title, 5, 20);
		doc.text(split1, 5, 50);
		doc.text(split2, 5, 100);
		doc.text(split3, 5, 150);
		doc.output('dataurlnewwindow');
	};

	const generateImage = async () => {
		const image = await toPng(html.current, {quality: 0.95});
		const doc = new jsPDF();

		doc.addImage(image, 'JPEG', 5, 22, 200, 160);
		doc.save();
	}

	return (
		<>
			<Head>
				<title>Accueil Big Trip</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
				<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet"/>
			</Head>
			<NavBar/>
			<div className="body">
				<div className="mt-[100px] mb-[20px] flex justify-between">
					<span id="title" className="text-black text-[50px] font-extrabold">{trip && trip.name}</span>
					<button onClick={generatePdf}
							className="py-2 px-4 bg-primary text-white rounded-xl hover:bg-hover-primary focus:outline-none focus:bg-hover-primary ease-in-out duration-500 hover:scale-105">
						Export trip
					</button>
				</div>
				<div className="bgImage">
					<Image src={trip?.photo}
						   className={`${styles.tripImageDetails} rounded-xl`}
						   layout="responsive"
						   alt="Picture home page"
						   width="2400"
						   height="1080"
						   blurDataURL="blur"
					/>
				</div>
				<div id="transport" className="activity mb-[20px]">
					<div className="mt-5">
						<div className="pt-1.5 pr-96 text-neutral-900 font-bold text-3xl">
							Transport
						</div>
						<RowTripDetails trip={trip?.TripTravel}/>
					</div>
				</div>
				<hr className="mt-8"/>
				<div id="logement" className="activity mb-[20px]">
					<div className="mt-5">
						<div className="pt-1.5 pr-96 text-neutral-900 font-bold text-3xl">
							Logement
						</div>
						<RowTripDetails trip={trip?.TripHousing}/>
					</div>
				</div>
				<hr className="mt-8"/>
				<div id="activite" className="activity mb-[170px]">
					<div className="mt-5">
						<div className="pt-1.5 pr-96 text-neutral-900 font-bold text-3xl">
							Activités
						</div>
						<RowTripDetails trip={trip?.TripActivity}/>
					</div>
				</div>
			</div>
			<div className="">
				<Footer/>
			</div>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
		</>
	);
}

export default Id;
