import NavBar from "@/components/menu/NavBar"
import Head from "next/head"
import Image from 'next/image';
import bgHome from '@/assets/images/bg-home.jpg';
import styles from '@/components/landing/LandingHeader.module.css';
import MultiStepForm from "@/components/form/MultistepForm";


const AddTrip = () => {
    return (
       <>
       <Head>
				<title>Accueil Big Trip</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
				<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet" />
			</Head>
			<NavBar />
            <div className="bgImage">
				<Image src={bgHome}
							 className={styles.landingImageCover}
							 layout="responsive"
							 alt="Picture home page"
							 width="2400"
							 height="1080"
							 placeholder="blur"
				/>
				<div className="flex flex-col items-center p-0 absolute w-full top-[180px]">
					<span className="text-white text-shadow font-medium text-[45px]">Lancez vous</span>
					<span className="text-white text-shadow font-bold text-[80px]">AJOUTEZ UN TRIP</span>
				</div>
			</div>
            <MultiStepForm/>
       </>
    )
}

export default AddTrip
