import Head from 'next/head'
import React, {useRef, useEffect} from 'react';
import NavBar from '@/components/menu/NavBar';
import LandingHeader from '@/components/landing/LandingHeader';
import CardTrip from '@/components/trip/cardTrip/CardTrip';
import CardHousing from '@/components/trip/cardHousing/CardHousing';
import Footer from '@/components/footer/Footer';
import Image from 'next/image';
import bgHome from '@/assets/images/bg-home.jpg';
import styles from '@/components/landing/LandingHeader.module.css';
import Maps from '@/components/maps/maps'
import {useMaps} from '@/context/mapsContext'
import {useSearch} from '@/context/searchContext'
import LodgingResult from '@/components/landing/LodgingResult'
import DirectionResult from '@/components/landing/DirectionResult';
import {useRouter} from 'next/router';
import TripService from '../../_services/trip';

export default function Home() {
	const mapsRef = useRef<HTMLDivElement>(null)
	const {setScrollRef, getUserGeolocation} = useMaps()
	const {activityMode, search} = useSearch()
	const [trip, setTrip] = React.useState<any>(null);
	const router = useRouter();
	useEffect(() => {
		setScrollRef(mapsRef)
		if (!router.isReady) return;
		const getTrip = async () => {
			const tripService = new TripService();
			try {
				const response = await tripService.getAllTrip();
				if (response.status === 200) {
					return response.data['hydra:member'];
				}
			} catch (error) {
				console.log(error);
			}
		};

		getTrip().then((trip) => {
			setTrip(trip);
		});

	}, [router.isReady]);
	return (
		<>
			<Head>
				<title>Accueil Big Trip</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
				<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet"/>
			</Head>
			<NavBar/>
			<div className="bgImage">
				<Image src="https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80"
					   className={`${styles.landingImageCover} rounded-b-2xl`}
					   layout="responsive"
					   alt="Picture home page"
					   width="2400"
					   height="1080"
					   blurDataURL="blur"
				/>
				<div className="flex flex-col items-center p-0 absolute w-full top-[180px]">
					<span className="text-white text-shadow font-medium text-[45px]">Helping Others</span>
					<span className="text-white text-shadow font-bold text-[80px]">LIVE & TRAVEL</span>
					<span
						className="text-white text-shadow font-normal text-[20px]">Special offers to suit your plan</span>
				</div>
			</div>
			<div className="body">
				<div className="contentHome">
					<LandingHeader/>
				</div>
				<div ref={mapsRef}>
					{activityMode == 1 ? search && <DirectionResult/> : <LodgingResult/>}
				</div>
				<div className="contentHome containerTrip ">
					<span className="text-black text-[32px] font-semibold">Maps</span>
					<Maps/>
				</div>
				<div className="contentHome containerTrip">
					{trip && (
						<span className="text-black text-[32px] font-semibold">Trip Public</span>
					)}
					<div className="containerTrip grid grid-cols-2 gap-6 mt-5">
						{trip && trip.map((data: any) => (
							<CardTrip key={data.id} trip={data}/>
						))}
					</div>
				</div>
			</div>
			<div className="">
				<Footer/>
			</div>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
		</>
	)
}
